# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Calleo Orthopédagogie
# Description of the Site
description: Devenir l’expert de ses apprentissages !
description1: Apprendre pour réussir, ça s’apprend.
description2: Retrouvez l’envie d’apprendre !

# URL of Image of the Site
site-image: assets/images/Calleo.png
# Keywords of the Site
site-keywords: apprentissage, dys, orthopedagogie, orthopedagogue, antony, 
# URL for the Image of custom Favicon
favicon-url: assets/images/Calleo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://img.freepik.com/photos-gratuite/etudiants-connaissant-bonne-reponse_329181-14271.jpg?w=2000
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@calleo-orthopedagogie.fr
telephone: 06 82 14 64 73
appel: +33682146473
facebook_username: geraldine.loty
twitter_username: 
instagram_username: geraldineloty
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-M14FET3SB4

# Disqus
disqus-shortname:

# Name of the Author
author-name: Géraldine Loty
# URL for the Image of the Author
author-image: assets/images/G_LOTY.jpg
livre-image: assets/images/DYS_adaptation2.jpg
livre-url: https://www.amazon.fr/DYS-Outils-adaptations-classe-Cycles/dp/2725643147
# 60 Words About the Author
author-about: Forte d’une expérience de plus de 20 ans dans l’enseignement en France et à l’étranger, j’ai toujours eu à cœur d’être au plus près des besoins des élèves en difficultés et/ou porteurs de troubles des apprentissages. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:
# Ajout du Logo
author-logo: assets/images/Calleo.png

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
